# Generated by Django 6.0.2 on 2026-02-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_id", models.IntegerField()),
                ("truckstop_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=2)),
                ("rack_id", models.IntegerField()),
                ("retail_price", models.DecimalField(decimal_places=3, max_digits=6)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["state", "city"], name="route_plann_state_30d23f_idx"
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="route_plann_latitud_e48f11_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "opis_id",
                            "truckstop_name",
                            "address",
                            "city",
                            "state",
                            "rack_id",
                        ),
                        name="unique_fuel_station",
                    )
                ],
            },
        ),
    ]
